<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartProductRepository extends EntityRepository
{
	public function hasItem($id, $userId)
	{
		$query = $this->getEntityManager()->createQuery(
                'SELECT cp FROM AppBundle:CartProduct cp WHERE cp.product = :id AND cp.user = :userId'
            )
			->setParameter('id', $id)
			->setParameter('userId', $userId);
        $cartProduct = $query->getResult();
        if ($cartProduct) {
        	return $cartProduct[0];
        }
        else {
        	return false;
        }
	}

    public function getUserCart($userId)
    {
        $query = $this->getEntityManager()->createQuery(
                'SELECT cp FROM AppBundle:CartProduct cp WHERE cp.user = :userId'
            )
            ->setParameter('userId', $userId);
        $cartProduct = $query->getResult();
        return $cartProduct;
    }
}
