<?php

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * UserOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOrderRepository extends EntityRepository
{
	public function findByType($id, $type)
	{
		$query = $this->getEntityManager()->createQuery(
                'SELECT O FROM AppBundle:UserOrder O WHERE O.user = :id AND O.status = :type 
                ORDER BY O.createAt DESC'
            );
        $query->setParameter('id', $id);
        $query->setParameter('type', $type);
        return $query->getResult();
	}
	
  public function deleteorder($id)
	{
		$query = $this->getEntityManager()->createQuery(
                'update AppBundle:UserOrder O set O.status=4 WHERE O.id = :id'
            );
        $query->setParameter('id', $id);         
        return $query->execute();
	}
	
	public function realdeleteorder($id)
	{
		$query = $this->getEntityManager()->createQuery(
                'delete from AppBundle:UserOrder O WHERE O.id = :id'
            );
        $query->setParameter('id', $id);       
        return $query->execute();
	}
}
