# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    checkout_user_id: CAIGOU_Dev
    checkout_key: 0ef0c283693b5968e0b7ff9aec5a72a1755cbd5a16bd8a4b5a1044049c26ea95
    curl_url: https://uat.paymentexpress.com/pxaccess/pxpay.aspx



services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    fos_user.profile.form.type:
        class: AppBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name : form.type , alias : fos_user_profile }

    app.form.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    user.on.login:
        class: AppBundle\EventListener\OnLoginListener
        arguments: [@request, @doctrine.orm.entity_manager, @security.context]
        scope: request
        tags:
            - { name: kernel.event_subscriber }

    product.click.increment:
        class: AppBundle\Service\ProductClikcIncrement
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"

    fos_user.doctrine_registry:
        alias: doctrine

    app.skip.checkout:
        class: AppBundle\Service\SkipToCheckout
        arguments: ['%checkout_user_id%', '%checkout_key%', '%curl_url%', @router]

    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

